# Generated by Django 2.1.2 on 2018-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0003_auto_20181011_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default='Please input description', max_length=200),
        ),
    ]
