# Generated by Django 2.1.2 on 2018-10-13 16:45

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0006_myidea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myidea',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
