# Generated by Django 2.1.2 on 2018-10-14 09:59

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0007_auto_20181014_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
