# Generated by Django 2.1.2 on 2018-10-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0008_auto_20181014_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='Please input description', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='preview_pic_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='card_type',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cloudsen_blog.CardType'),
            preserve_default=False,
        ),
    ]
