# Generated by Django 2.1.2 on 2018-10-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0009_auto_20181028_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_pic_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
