# Generated by Django 2.1.2 on 2018-10-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0010_auto_20181028_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_color',
            field=models.CharField(choices=[('dark', 'text has gray color'), ('light', 'text has white color ')], default='dark', max_length=30),
        ),
    ]
