# Generated by Django 2.1.2 on 2018-10-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0011_article_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_color',
            field=models.CharField(choices=[('gray', 'gray color'), ('light', 'white color '), ('dark', 'black color')], default='gray', max_length=30),
        ),
    ]
