# Generated by Django 2.1.2 on 2018-10-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0012_auto_20181028_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_color',
            field=models.CharField(choices=[('text-muted', 'gray color'), ('text-light', 'white color '), ('text-dark', 'black color')], default='gray', max_length=30),
        ),
    ]
