# Generated by Django 2.1.2 on 2018-11-08 04:05

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0014_auto_20181107_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', markdownx.models.MarkdownxField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
