# Generated by Django 2.1.2 on 2018-11-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0015_sitetimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetimeline',
            name='create_time',
            field=models.DateTimeField(),
        ),
    ]
