# Generated by Django 2.1.2 on 2018-11-08 13:33

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0017_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('introduce', markdownx.models.MarkdownxField()),
                ('site_url', models.CharField(max_length=300)),
                ('avatar_url', models.CharField(max_length=300)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
