# Generated by Django 2.1.2 on 2018-11-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsen_blog', '0018_friendslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_color',
            field=models.CharField(choices=[('text-muted', 'muted color'), ('text-light', 'white color '), ('text-dark', 'black color'), ('text-gray', 'gray color')], default='gray color', max_length=30),
        ),
    ]
